title: <p align="center">Trang Tran </p>
logo: "/images/image.png?raw=true"

description:
<p align="justify">
  A data enthusiast wants to find hard problems that data can solve.
  A lifelong learner wants to make my life a learning journey.
  <br><br>
  Email: trangtran.work.23@gmail.com
  <br>
  <a href="https://www.linkedin.com/in/trangtran1995/">  My LinkedIn Profile</a>
   </p>
  <br>
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
